# Generated by Django 5.0.3 on 2024-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('rol', models.CharField(max_length=40)),
                ('diabetes', models.BooleanField(default=False)),
            ],
        ),
    ]
