# Generated by Django 5.0.4 on 2024-04-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('imagen_base64', models.TextField()),
            ],
        ),
    ]
