# Generated by Django 5.0.4 on 2024-04-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_diagnostico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='imagen_base64',
            new_name='imagen',
        ),
    ]
