# Generated by Django 5.0.4 on 2024-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_imagen_base64_diagnostico_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='observaciones',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='resultado',
            field=models.CharField(default='no retinopatia', max_length=40),
            preserve_default=False,
        ),
    ]
