# Generated by Django 5.0.4 on 2024-05-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_diagnostico_observaciones_diagnostico_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('fuente', models.TextField()),
            ],
        ),
    ]
